### ISSUE TITLE
Return peer stats in results - Enhancement Request

### ISSUE THREAD

**Issue by btbenedi** [grantholle/rarbg#11]
Would it be possible for this to also return peer stats? If you're not actively updating this anymore, I'll just fork, but figured I'd check first 

EDIT: Based on torrentapi.org docs, looks like that isn't even returning that data, so I doubt this is possible, guess I'll have to go old school scraper for now, feel free to close

**Comment by grantholle** [comment]
Yeah, it doesn't provide the count. You can sort by seeders, with the results with the most seeders being first...

```js
rarbg.search({
  search_string: 'star wars',
  sort: 'seeders'
})
```

**Comment by grantholle** [comment]
Actually, there is a way to return more details about the search results. Adding a `format` key with `json_extended`.

```js
rarbg.search({
  search_string: 'star wars',
  format: 'json_extended'
}).then(console.log)
```

```json
{
  "torrent_results": [
    {
      "title": "Lone.Star.Law.S08E00.Boundary.Wars.720p.WEBRip.x264-KOMPOST[rartv]",
      "category": "TV HD Episodes",
      "download": "magnet:?xt=...",
      "seeders": 0,
      "leechers": 1,
      "size": 1193322918,
      "pubdate": "2020-10-05 18:35:19 +0000",
      "episode_info": {
        "imdb": "tt5796728",
        "tvrage": null,
        "tvdb": "312613",
        "themoviedb": "67095"
      },
      "ranked": 1,
      "info_page": "https://torrentapi.org/redirect_to_info.php?token=glk58mxds2&p=2_3_1_8_6_9_1__64eea83a13"
    }
  ]
}
```

**Comment by btbenedi** [comment]
Oh awesome, even gets age and episode identifiers, I must've missed that in the docs, thanks!
